# Generated by Django 4.2.7 on 2023-11-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.TextField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='neighborhood',
            field=models.TextField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
